# Generated by Django 5.1.3 on 2024-11-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='assigned_students',
            field=models.ManyToManyField(related_name='assigned_homework', to='assignment.student'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('homework', 'student')},
        ),
    ]
